### ISSUE TITLE
CreditCardPaymentMethodDetails

### ISSUE THREAD

**Issue by remyvv** [ingpsp/ing-php#7]
Hi,

In using this library i noticed that the CreditCardPaymentMethodDetails class is missing all information provided by the ING Kassa Compleet API.

Attached to this issue is a patch file containing a more complete version of the CreditCardPaymentMethodDetails class.

[ingpsp-add-creditcard-details.patch.txt](https://github.com/ingpsp/ing-php/files/2795148/ingpsp-add-creditcard-details.patch.txt)

**Comment by ingpsp** [comment]
Thanks! We will patch it.
